import pandas as pd

#  CONFIGURATION 
# The prediction file generated by deep_lerning.py or test_train.py
INPUT_CSV = "predictions_best_model_fold7.csv"
# The final Kaggle-compatible submission file
OUTPUT_CSV = "submission.csv"

#  LOAD PREDICTIONS 
try:
    df = pd.read_csv(INPUT_CSV)

    #  CHECK REQUIRED COLUMNS 
    required_cols = ['row_id', 'predicted_category', 'predicted_misconception']
    if not all(col in df.columns for col in required_cols):
        raise ValueError(f"Input CSV must contain the following columns: {required_cols}")

    #  BUILD FINAL SUBMISSION 
    # Select the required columns and rename them for the submission format
    submission_df = df[['row_id', 'predicted_category', 'predicted_misconception']].copy()
    submission_df.rename(columns={
        'predicted_category': 'Category',
        'predicted_misconception': 'Misconception'
    }, inplace=True)

    #  SAVE TO FILE 
    submission_df.to_csv(OUTPUT_CSV, index=False)
    print(f"Submission file '{OUTPUT_CSV}' created successfully from '{INPUT_CSV}'.")

except FileNotFoundError:
    print(f"Error: Input file '{INPUT_CSV}' not found. Please run the evaluation script first to generate predictions.")
except Exception as e:
    print(f"An error occurred: {e}")
